#!/bin/sh

#rmmod nvme nvme_tcp nvme_core nvme_fabrics
sudo modprobe nvme_core
sudo modprobe nvme
sudo modprobe nvme_fabrics
sudo modprobe nvme_tcp
app_port=4420
subnqn=nqn.2014-08.org.nvmexpress.discovery
ipaddrserver=127.0.0.2
config=target-config.json
backing_file=disk1      # sparse file to use (or create)
backing_file_size=65536 # in MB

sudo losetup -f $backing_file
if
    [ "$?" = 0 ]; then
    echo backing file at $backing_file
    echo devices:
    echo
    sudo losetup -l
else
    echo problem with loop dev creation from $backing_file
    if [ -e $backing_file ]; then
	echo old backing file $backing_file?  Bailing out.
	exit 1
    fi
    echo creating file at $backing_file
    dd if=/dev/zero of=$backing_file count=1 bs=1M seek=$backing_file_size
fi


# /> cd subsystems
# /subsystems> create nvme_subsystem
# /subsystems> cd nvme_subsystem
# /subsystems/nvme_subsystem> set attr allow_any_host=1
# Parameter allow_any_host is now '1'.
# /subsystems/nvme_subsystem> cd namespaces
# /subsystems/n...em/namespaces> create nsid=1
# /subsystems/n...em/namespaces> cd 1
# /subsystems/n.../namespaces/1> set device path=/dev/nvme0n1
# Parameter path is now '/dev/nvme0n1'.
# /subsystems/n.../namespaces/1> enable
# The Namespace has been enabled.
# /subsystems/n.../namespaces/1> cd ../../../..
# /> cd ports
# /ports> create 1
# /ports> cd 1
# /ports/1> set addr adrfam=ipv4
# Parameter adrfam is now 'ipv4'.
# /ports/1> set addr trtype=tcp
# Parameter trtype is now 'tcp'.
# /ports/1> set addr trsvcid=4420
# Parameter trsvcid is now '4420'.
# /ports/1> set addr traddr=13.100.0.13
# Parameter traddr is now '13.100.0.13'.
# /ports/1> cd subsystems
# /ports/1/subsystems> create nvme_subsystem

if [ -f $config ]; then
    echo found $config
else
    echo creating $config
    echo
    tee $config <<EOF
{
  "hosts": [],
  "ports": [
    {
      "addr": {
        "adrfam": "ipv4",
        "traddr": "127.0.0.2",
        "treq": "not specified",
        "trsvcid": "4420",
        "trtype": "tcp"
      },
      "portid": 1,
      "referrals": [],
      "subsystems": [
        "loop0"
      ]
    }
  ],
  "subsystems": [
    {
      "allowed_hosts": [],
      "attr": {
        "allow_any_host": "1",
        "cntlid_max": "65519",
        "cntlid_min": "1",
        "firmware": "6.2.0-rc",
        "ieee_oui": "0x000000",
        "model": "Linux",
        "pi_enable": "0",
        "qid_max": "128",
        "serial": "a87e7a41bcc248283fde",
        "version": "1.3"
      },
      "namespaces": [
        {
          "device": {
            "nguid": "00000000-0000-0000-0000-000000000000",
            "path": "/dev/loop0",
            "uuid": "d30f23b9-4cea-4b58-b52b-d1a62a3b9f83"
          },
          "enable": 1,
          "nsid": 1
        }
      ],
      "nqn": "loop0"
    }
  ]
}
EOF
fi

echo loading $config
sudo nvmetcli restore $config
sudo nvme discover -t tcp -a $ipaddrserver -s $app_port

sudo nvme connect -t tcp -a $ipaddrserver -s $app_port -n $subnqn

sudo nvme disconnect -n $subnqn
sudo /usr/local/bin/nvmetcli clear
